### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by yong86** [apiaryio/emscripten-docker#16]
Hello, 
**I get this error when trying to compile .c file** 

root@984e88feb6cb:/test# emconfigure ./configure
ERROR:root:Exception thrown when invoking Popen in configure with args: "./confi
gure"!
Traceback (most recent call last):
  File "/usr/local/bin/emconfigure", line 13, in <module>
    emconfigure.run()
  File "/emscripten/emconfigure.py", line 46, in run
    shared.Building.configure(sys.argv[1:])
  File "/emscripten/tools/shared.py", line 1527, in configure
    process = Popen(args, stdout=None if EM_BUILD_VERBOSE_LEVEL >= 2 else stdout
, stderr=None if EM_BUILD_VERBOSE_LEVEL >= 1 else stderr, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied

**Any Help!**
Thanks

**Comment by w-vi** [comment]
Please can you provide me the docker command used to spin up the container too? Is the project correctly mounted?

**Comment by yong86** [comment]
Thanks for your help.
What I did :
1- docker run 984e88feb6cb container
2- docker exec -it 984e88feb6cb /bin/bash
3- copying the project inside the container .
4- run emconfigure ./configure

**Comment by w-vi** [comment]
I suspect that the project is not correctly mounted/copied. Can you try running it by:
`docker run --rm -v $(pwd):/src -ti apiaryio/emcc:1.37 /bin/bash` and then inside the container run the configure?

**Comment by w-vi** [comment]
The project needs to be under the `/src` directory inside the container. The above command mounts the current directory (the one with project to be build) to `/src` inside the container.
